### ISSUE TITLE
Sharing fork of SaltyNX

### ISSUE THREAD

**Issue by masagrator** [jugeeya/UltimateTrainingModpack#17]
Is it possible to share your fork of SaltyNX that compiles to nsp sysmodule?

**Comment by jugeeya** [comment]
I would, but actually this method does not work for the latest SaltyNX (which the training modpack does not use yet). Since I'm planning to move to using the latest SaltyNX, I will either figure out how to make the NSP work properly or revert back to using the `kip` format. In the former case, I will probably make a PR to SaltyNX that produces the NSP as well.

**Comment by masagrator** [comment]
Latest SaltyNX doesn't work with atm 0.9.2 for me (0.9.1 without issue). So it's maybe better to stay with this version atm. Or maybe something on my Switch doesn't work.

**Comment by jugeeya** [comment]
Have you tried with the actual latest? (There was a long period of time when the latest commits did not really work on any firmware) If you prefer the NSP for some other reason, please let me know, and I may push a fork that makes an NSP installable version.

**Comment by masagrator** [comment]
Yes, I've compiled it yesterday and today.
If you can, I'll apreciate that.

**Comment by jugeeya** [comment]
https://github.com/shinyquagsire23/SaltyNX/pull/8
