### ISSUE TITLE
exefs missing from release

### ISSUE THREAD

**Issue by MrMagoffin** [jugeeya/UltimateTrainingModpack#281]
Latest release (3.1) zip does not contain exefs and thus when installed has no effect when running the game

**Comment by Craftyawesome** [comment]
This is intentional https://discord.com/channels/407970595418931200/407970595423125506/904042268749594644
"We don't want to bundle Skyline with any mods anymore to avoid the issue that happened just recently, where Atmosphere broke Skyline so it needed to be updated. This is mostly for people who use multiple mods that depend on Skyline where they might use an old version of Skyline that'd break.
You really just have to read the install instructions a bit more carefully. It's all there."

**Comment by MrMagoffin** [comment]
ah, sorry, my bad
