### ISSUE TITLE
Character-specific Toggles

### ISSUE THREAD

**Issue by jugeeya** [jugeeya/UltimateTrainingModpack#33]
Show toggles for parameters relating to character-specific modes. Only show them when the character in question is in the match.

- Wario: half/full waft
- Cloud: limit
- Joker: Arsene
- Shulk: monado arts
- Hero: oomph/psyche up/acceleratle

**Comment by Yikarur** [comment]
Possible additions that come to my mind (lots of ideas, not sure if it's even possible to implement them all)
- Bowser/Charizard: Never decaying Flame Thrower
- Wii Fit Trainer: Deep Breathing   
- ROB Laser Charge Level
- Olimar: Next Pikmin Plug
- Rosalina: Luma Health (+ infinite health)
- Villager/Isabelle: Pocketed Item
- Kirby: Hats (independed of the opponent.. I don't think thats possible because your ability disappears in Squad Strike as well if the opponent switches character)
- Always Full Charged Option for Dark Samus, DK, Sheik, Mewtwo,  Lucario, Wii Fit Trainer, Squirtle, Gyro, Mario, anything I might have forgot

**RNG:**
- Luigi: Always Misfire with Luigi
- Peach/Daisy: Always same item
- GaW: Always 9 
- Hero: Select Specials that pop-up every time

**Items:** 
- In Hand when L+R Start: Banana / Gyro / Turnip / Saturn / Bob-Omb / Grenade / (Toon/Young) Links Bomb / Holy Water (Fire/Aura)  / Metal Blade / Rear Egg / Mecha Koopa / Pac Man Items (Cherry/Strawberry/Orange/Apple/Melon/Boss Galaxian/Bell/Key) / Robins Books / Levin Sword

**Comment by mentalityrl** [comment]
I like those ideas. Especially toggling Arsene manually.

**Comment by AZ-7** [comment]
Also one to consider is Full MP hero

**Comment by SondreElg** [comment]
Letting Robin start with Levin Sword charged in training mode would be nice. We could finally stop having to SD every time we want to attempt a combo with it.

Oh, and maybe a toggle for infinite tome/Levin Sword uses. Though that would probably not be as useful if savestate tracked Robin's tome/Levin Sword usage, but I'm not sure how doable that is.

**Comment by jugeeya** [comment]
Many of these are addressed by Buff Options in the latest beta, and we have a separate issue tracking the remaining items.
