### ISSUE TITLE
Pyra/Mythra have Inverted DI for Mii Brawler Down Throw

### ISSUE THREAD

**Issue by MetalNeo** [jugeeya/UltimateTrainingModpack#432]
When Mii Brawler down throws Pyra or Mythra, their DI is inverted from the selection in the menu (away instead of in and in instead of away). This doesn't seem to occur when Pyra/Mythra are hit by Mii Brawler's other moves.

**Comment by asimon-1** [comment]
This is expected behavior. The "In" and "Away" directions are not related to the facing or launch directions, but rather the relative positions of the two characters. In the vast amount of cases, this works as you'd expect. However, some down throws and up throws actually place the opponent behind the fighter at the time of the launch, which leads to an unintuitive DI selection.

You can use the "Left" or "Right" DI directions as a workaround for this issue.
