### ISSUE TITLE
Address clippy warnings

### ISSUE THREAD

**Issue by asimon-1** [jugeeya/UltimateTrainingModpack#439]
We should run clippy and address all warnings. Clippy can be revived with the following changes to `.vscode/settings.json`. We should also probably gitignore the `.vscode/` folder so we don't pick up individual contributors workspace configs.
```diff
@@ -1,6 +1,7 @@
 {
     "rust-analyzer.checkOnSave.overrideCommand": [
-        "xargo",
+        "cargo",
+        "+nightly",
         "clippy",
         "--workspace",
         "--message-format=json",
 }
```

**Comment by jugeeya** [comment]
> We should also probably gitignore the .vscode/ folder so we don't pick up individual contributors workspace configs.

I put it because I wanted people opening the Training Modpack to get clippy working without any other need for setup. I wonder if there is a better way of doing this. Also though, it may be okay to keep, as this folder can contain only the settings to override for the workspace in question, and otherwise folks can edit their global settings, etc.

**Comment by jugeeya** [comment]
Done with https://github.com/jugeeya/UltimateTrainingModpack/pull/451
