### ISSUE TITLE
Some GFX effects happening later

### ISSUE THREAD

**Issue by gnaomo** [jugeeya/UltimateTrainingModpack#56]
Found with peach side b heart and falcon up b explosion
![ezgif-3-acd0a931ed14](https://user-images.githubusercontent.com/38522864/82048146-5d311980-96b4-11ea-806f-8560feace54f.gif)
![ezgif-3-1f367c1d4f33](https://user-images.githubusercontent.com/38522864/82048148-5e624680-96b4-11ea-9c0a-60b6d67fb28e.gif)

**Comment by JonasBjordal** [comment]
If I remember correctly this applies to a lot of other moves like Link arrow and an extreme example is Cloud's Cross Slash where the visual gets stuck indefinitely. Pretty harmless bug but can be a bit distracting in some scenarios

**Comment by jugeeya** [comment]
Yeah, I hate this bug, it's from here:

https://github.com/jugeeya/UltimateTrainingModpack/blob/master/src/hitbox_visualizer/mod.rs#L236-L241

I can simplify this a bit and hopefully it comes out nice. Otherwise, do you think turning off effects always when hitbox visualization would be better? At least it wouldn't seem buggy.

**Comment by jugeeya** [comment]
Fixed in latest commit, I'll upload new beta later.
