### ISSUE TITLE
No option for ledge hang

### ISSUE THREAD

**Issue by KyleMennie** [jugeeya/UltimateTrainingModpack#88]
The "None" ledge option will perform a neutral getup before ledge invincibility ends. It would be nice for it to continually hang on ledge.

**Comment by asimon-1** [comment]
This could effectively be accomplished with a long ledge delay (e.g. 9000 frames). However, since the ledge delay is coded as a u32 bitmask, I think the maximum delay with the current delay framework is 32. 

It may not be that much work to change it from a u32 bitmask to a lone u32 - I'll work on this.

To keep the ability to randomly select a ledge delay, maybe we could add a boolean flag that toggles the behavior between "delay X number of frames" and "delay between 0 and X number of frames"? I'm not sure its all that useful to be able to randomly select between particular delay values so this seems a decent replacement, though I could be wrong.

**Comment by asimon-1** [comment]
It turned out to be simpler to execute this as an action rather than a delay. 

https://github.com/asimon-1/UltimateTrainingModpack/blob/ledge-hang/src/training/ledge.rs

**Comment by asimon-1** [comment]
A bug that still need to be worked out: 
The CPU now correctly waits on ledge if the WAIT option is selected, but only if no other ledge option has been selected yet. Once another ledge option gets picked, the CPU will perform a neutral getup instead of WAIT when deciding what to do on future ledge scenarios, even when neutral getup isn't selected in the menu.

**Comment by KyleMennie** [comment]
Awesome, thanks for the help so far!

Would be great if you're able to figure out that bug as well. Randomly waiting along with other getup options would be useful for mixing in ledge punishes when practicing ledge trapping!

**Comment by jugeeya** [comment]
Merged thanks to @asimon-1 !
